config/routes.rb
Rails.application.routes.draw do
  get 'reset_passwords/new'

  # get 'users/new'

  root to: "homes#index"
  get "page", to: "homes#page"
  resources :users, only: [:new, :create] do
  	member do
    	get :activate
  	end
  end

  resources :reset_passwords, only: [:new, :create, :update, :edit]
  resources :sessions, only: [:new, :create, :destroy]
  get '/sign_up', to: 'users#new', as: :sign_up
	get '/log_in', to: 'sessions#new', as: :log_in
	delete '/log_out', to: 'sessions#destroy', as: :log_out
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  private

	def not_authenticated
	  flash[:warning] = 'You have to authenticate to access this page.'
	  redirect_to log_in_path
	end
	
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def page
  end
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  skip_before_filter :require_login
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    @user.deliver_reset_password_instructions! if @user
    flash[:success] = 'Instructions have been sent to your email.'
    redirect_to log_in_path
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    not_authenticated if @user.blank?
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    not_authenticated && return if @user.blank?

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password!(params[:user][:password])
      flash[:success] = 'Password was successfully updated.'
      redirect_to log_in_path
    else
      render "edit"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :require_login, except: [:destroy]
	
  def new
  end

  def create
    if login(params[:email], params[:password], params[:remember_me])
      flash[:success] = 'Welcome back!'
      redirect_back_or_to root_path
    else
      flash.now[:warning] = 'E-mail and/or password is incorrect.'
      render 'new'
    end
  end

  def destroy
    logout
    flash[:success] = 'See you!'
    redirect_to log_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :activate]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def activate
    if @user = User.load_from_activation_token(params[:id])
      @user.activate!
      flash[:success] = 'User was successfully activated.'
      redirect_to log_in_path
    else
      flash[:warning] = 'Cannot activate this user.'
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reset_passwords_helper.rb
module ResetPasswordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<h1>Welcome</h1>

app/views/homes/page.html.erb
<h1>Welcome!</h1>

<p>Restricted area for authorized users only.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthlogicExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<div id="navbar">
	  <ul class="nav navbar-nav">
	    <% if current_user %>
	      <li><%= link_to 'Secret Page', page_path %></li>
	    <% else %>
	      <li><%= link_to 'Sign Up', sign_up_path %></li>
	      <li><%= link_to 'Log In', log_in_path %></li>
	    <% end %>
	  </ul>
	  <% if current_user %>
	    <ul class="nav navbar-nav pull-right">
	      <li><span><%= current_user.name %></span></li>
	      <li><%= link_to 'Log Out', log_out_path, method: :delete %></li>
	    </ul>
	  <% end %>
	</div>

	<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/reset_passwords/edit.html.erb
<h1>Choose a new password</h1>

    <%= form_for @user, url: reset_password_path(@token), method: :patch do |f| %>
      <%= render 'shared/errors', object: @user %>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
      </div>

        <%= f.submit 'Set password', class: 'btn btn-primary btn-lg' %>
    <% end %>

app/views/reset_passwords/new.html.erb
<h1>Reset Password</h1>

    <%= form_tag reset_passwords_path, method: :post do %>
      <div class="form-group">
        <%= label_tag :email %>
        <%= text_field_tag :email, nil, class: 'form-control', required: true %>
      </div>

      <%= submit_tag "Send reset instructions", class: 'btn btn-primary btn-lg' %>
    <% end %>

app/views/users/new.html.erb
<h1>Registration</h1>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
  </div>
  <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>